-- MySQL Script generated by MySQL Workbench
-- Fri Feb  8 15:19:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id_client` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `civilite` VARCHAR(12) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `adresse_mail` VARCHAR(150) NOT NULL,
  `numero_telephone` VARCHAR(12) NOT NULL,
  `mot_de_passe` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `adresse_mail_UNIQUE` (`adresse_mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adresse` (
  `id_adresse` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_voie` INT UNSIGNED NOT NULL,
  `nom_voie` VARCHAR(150) NOT NULL,
  `code_postal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_adresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`choix_client_livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`choix_client_livraison` (
  `id_choix_livraison` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_client` INT UNSIGNED NOT NULL,
  `id_adresse` INT UNSIGNED NOT NULL,
  `option_livraison` VARCHAR(100) NOT NULL,
  `paiement_livraison` TINYINT(1) UNSIGNED NOT NULL,
  INDEX `fk_id_adresse_idx` (`id_adresse` ASC) VISIBLE,
  PRIMARY KEY (`id_choix_livraison`),
  CONSTRAINT `fk_id_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_adresse`
    FOREIGN KEY (`id_adresse`)
    REFERENCES `mydb`.`adresse` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facture` (
  `id_facture` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chemin_facture` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_facture`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizzeria` (
  `id_pizzeria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_pizzeria` VARCHAR(100) NOT NULL,
  `id_adresse` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pizzeria`),
  INDEX `fk_id_adresse_idx` (`id_adresse` ASC) VISIBLE,
  CONSTRAINT `fk_id_adresse`
    FOREIGN KEY (`id_adresse`)
    REFERENCES `mydb`.`adresse` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `numero_commande` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_client` INT UNSIGNED NOT NULL,
  `montant` DECIMAL(9,2) UNSIGNED NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `choix_livraison` INT UNSIGNED NOT NULL,
  `id_facture` INT UNSIGNED NOT NULL,
  `id_pizzeria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero_commande`),
  INDEX `fk_ref_client_idx` (`ref_client` ASC) VISIBLE,
  INDEX `fk_choix_livraison_idx` (`choix_livraison` ASC) VISIBLE,
  INDEX `fk_commande_facture1_idx` (`id_facture` ASC) VISIBLE,
  INDEX `fk_pizzeria_id_idx` (`id_pizzeria` ASC) VISIBLE,
  CONSTRAINT `fk_ref_client`
    FOREIGN KEY (`ref_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_choix_livraison`
    FOREIGN KEY (`choix_livraison`)
    REFERENCES `mydb`.`choix_client_livraison` (`id_choix_livraison`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_id`
    FOREIGN KEY (`id_facture`)
    REFERENCES `mydb`.`facture` (`id_facture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzeria_id`
    FOREIGN KEY (`id_pizzeria`)
    REFERENCES `mydb`.`Pizzeria` (`id_pizzeria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employe` (
  `id_employe` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `civilite` VARCHAR(12) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `fonction` VARCHAR(100) NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `commande_en_traitement` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_employe`),
  INDEX `fk_commande_traitement_idx` (`commande_en_traitement` ASC) VISIBLE,
  CONSTRAINT `fk_commande_traitement`
    FOREIGN KEY (`commande_en_traitement`)
    REFERENCES `mydb`.`commande` (`numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `id_produit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NOT NULL,
  `description` VARCHAR(500) NULL,
  `categorie` VARCHAR(100) NOT NULL,
  `prix_ttc` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_produit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `id_media` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NOT NULL,
  `type_media` VARCHAR(50) NOT NULL,
  `chemin_media` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_media`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recette` (
  `id_recette` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reference_produit` INT UNSIGNED NOT NULL,
  `recette` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`id_recette`),
  INDEX `fk_reference_produit_idx` (`reference_produit` ASC) VISIBLE,
  CONSTRAINT `fk_reference_produit`
    FOREIGN KEY (`reference_produit`)
    REFERENCES `mydb`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contenu_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contenu_commande` (
  `id_commande` INT UNSIGNED NOT NULL,
  `id_produit` INT UNSIGNED NOT NULL,
  `quantite_produit` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_commande`, `id_produit`),
  INDEX `fk_id_produit_idx` (`id_produit` ASC) VISIBLE,
  CONSTRAINT `fk_id_commande`
    FOREIGN KEY (`id_commande`)
    REFERENCES `mydb`.`commande` (`numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_produit`
    FOREIGN KEY (`id_produit`)
    REFERENCES `mydb`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etat_paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etat_paiement` (
  `id_etat_paiement` INT NOT NULL AUTO_INCREMENT,
  `ref_commande` INT UNSIGNED NOT NULL,
  `etat_paiement` VARCHAR(50) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_etat_paiement`),
  INDEX `fk_ref_commande_idx` (`ref_commande` ASC) VISIBLE,
  CONSTRAINT `fk_ref_commande`
    FOREIGN KEY (`ref_commande`)
    REFERENCES `mydb`.`commande` (`numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etat_preparation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etat_preparation` (
  `id_etat_preparation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_commande` INT UNSIGNED NOT NULL,
  `etat_paiement` VARCHAR(50) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_etat_preparation`),
  INDEX `fk_ref_commande_idx` (`ref_commande` ASC) VISIBLE,
  CONSTRAINT `fk_ref_commande`
    FOREIGN KEY (`ref_commande`)
    REFERENCES `mydb`.`commande` (`numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`illustration_recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`illustration_recette` (
  `id_illustration_recette` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_recette` INT UNSIGNED NOT NULL,
  `ref_media` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_illustration_recette`),
  INDEX `fk_ref_recette_idx` (`ref_recette` ASC) VISIBLE,
  INDEX `fk_ref_media_idx` (`ref_media` ASC) VISIBLE,
  CONSTRAINT `fk_ref_recette`
    FOREIGN KEY (`ref_recette`)
    REFERENCES `mydb`.`recette` (`id_recette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_media`
    FOREIGN KEY (`ref_media`)
    REFERENCES `mydb`.`media` (`id_media`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`illustration_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`illustration_produit` (
  `id_illustration_produit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_produit` INT UNSIGNED NOT NULL,
  `ref_media` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_illustration_produit`),
  INDEX `fk_ref_produit_idx` (`ref_produit` ASC) VISIBLE,
  INDEX `fk_ref_media_idx` (`ref_media` ASC) VISIBLE,
  CONSTRAINT `fk_ref_produit`
    FOREIGN KEY (`ref_produit`)
    REFERENCES `mydb`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_media`
    FOREIGN KEY (`ref_media`)
    REFERENCES `mydb`.`media` (`id_media`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `id_stock` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `categorie` VARCHAR(45) NULL,
  `quantite_restante` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_stock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`composition_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`composition_produit` (
  `id_produit` INT UNSIGNED NOT NULL,
  `id_ingredient` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_produit`, `id_ingredient`),
  INDEX `fk_id_produit_idx` (`id_produit` ASC) VISIBLE,
  CONSTRAINT `fk_id_produit`
    FOREIGN KEY (`id_produit`)
    REFERENCES `mydb`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ingredient`
    FOREIGN KEY (`id_ingredient`)
    REFERENCES `mydb`.`stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
