-- MySQL Script generated by MySQL Workbench and adapted by Ludophilia
-- Fri Feb  8 18:44:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE IF NOT EXISTS `6db` DEFAULT CHARACTER SET utf8 ;
USE `6db` ;

CREATE TABLE IF NOT EXISTS `6db`.`client` (
  `id_client` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `civilite` VARCHAR(12) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `adresse_mail` VARCHAR(150) NOT NULL,
  `numero_telephone` VARCHAR(12) NOT NULL,
  `mot_de_passe` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `adresse_mail_UNIQUE` (`adresse_mail` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`adresse` (
  `id_adresse` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_voie` INT UNSIGNED NOT NULL,
  `nom_voie` VARCHAR(150) NOT NULL,
  `code_postal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_adresse`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`choix_client_livraison` (
  `id_choix_livraison` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_client` INT UNSIGNED NOT NULL,
  `id_adresse` INT UNSIGNED NOT NULL,
  `option_livraison` VARCHAR(100) NOT NULL,
  `paiement_livraison` TINYINT(1) UNSIGNED NOT NULL,
  INDEX `fk_id_adresse_idx` (`id_adresse` ASC),
  PRIMARY KEY (`id_choix_livraison`),
  CONSTRAINT `fk_id_client_choix_client_livraison`
    FOREIGN KEY (`id_client`)
    REFERENCES `6db`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_adresse_choix_client_livraison`
    FOREIGN KEY (`id_adresse`)
    REFERENCES `6db`.`adresse` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`facture` (
  `id_facture` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chemin_facture` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_facture`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`pizzeria` (
  `id_pizzeria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_pizzeria` VARCHAR(100) NOT NULL,
  `id_adresse` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pizzeria`),
  INDEX `fk_id_adresse_idx` (`id_adresse` ASC),
  CONSTRAINT `fk_id_adresse_pizzeria`
    FOREIGN KEY (`id_adresse`)
    REFERENCES `6db`.`adresse` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`commande` (
  `numero_commande` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_client` INT UNSIGNED NOT NULL,
  `montant` DECIMAL(9,2) UNSIGNED NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `choix_livraison` INT UNSIGNED NOT NULL,
  `id_facture` INT UNSIGNED NOT NULL,
  `id_pizzeria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero_commande`),
  INDEX `fk_ref_client_idx` (`ref_client` ASC),
  INDEX `fk_choix_livraison_idx` (`choix_livraison` ASC),
  INDEX `fk_commande_facture1_idx` (`id_facture` ASC),
  INDEX `fk_pizzeria_id_idx` (`id_pizzeria` ASC),
  CONSTRAINT `fk_ref_client_commande`
    FOREIGN KEY (`ref_client`)
    REFERENCES `6db`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_choix_livraison_commande`
    FOREIGN KEY (`choix_livraison`)
    REFERENCES `6db`.`choix_client_livraison` (`id_choix_livraison`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_id_commande`
    FOREIGN KEY (`id_facture`)
    REFERENCES `6db`.`facture` (`id_facture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzeria_id_commande`
    FOREIGN KEY (`id_pizzeria`)
    REFERENCES `6db`.`pizzeria` (`id_pizzeria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`employe` (
  `id_employe` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `civilite` VARCHAR(12) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `fonction` VARCHAR(100) NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `commande_en_traitement` INT UNSIGNED NULL,
  PRIMARY KEY (`id_employe`),
  INDEX `fk_commande_traitement_idx` (`commande_en_traitement` ASC),
  CONSTRAINT `fk_commande_traitement_employe`
    FOREIGN KEY (`commande_en_traitement`)
    REFERENCES `6db`.`commande` (`numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`produit` (
  `id_produit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NOT NULL,
  `description` VARCHAR(500) NULL,
  `categorie` VARCHAR(100) NOT NULL,
  `prix_ttc` DECIMAL(6,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_produit`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`media` (
  `id_media` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NOT NULL,
  `type_media` VARCHAR(50) NOT NULL,
  `chemin_media` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_media`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`recette` (
  `id_recette` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reference_produit` INT UNSIGNED NOT NULL,
  `recette` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`id_recette`),
  INDEX `fk_reference_produit_idx` (`reference_produit` ASC),
  CONSTRAINT `fk_reference_produit_recette`
    FOREIGN KEY (`reference_produit`)
    REFERENCES `6db`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`contenu_commande` (
  `id_commande` INT UNSIGNED NOT NULL,
  `id_produit` INT UNSIGNED NOT NULL,
  `quantite_produit` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_commande`, `id_produit`),
  INDEX `fk_id_produit_idx` (`id_produit` ASC),
  CONSTRAINT `fk_id_commande_contenu_commande`
    FOREIGN KEY (`id_commande`)
    REFERENCES `6db`.`commande` (`numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_produit_contenu_commande`
    FOREIGN KEY (`id_produit`)
    REFERENCES `6db`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`etat_paiement` (
  `id_etat_paiement` INT NOT NULL AUTO_INCREMENT,
  `ref_commande` INT UNSIGNED NOT NULL,
  `etat_paiement` VARCHAR(50) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_etat_paiement`),
  INDEX `fk_ref_commande_idx` (`ref_commande` ASC),
  CONSTRAINT `fk_ref_commande_etat_paiement`
    FOREIGN KEY (`ref_commande`)
    REFERENCES `6db`.`commande` (`numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`etat_preparation` (
  `id_etat_preparation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_commande` INT UNSIGNED NOT NULL,
  `etat_preparation` VARCHAR(50) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_etat_preparation`),
  INDEX `fk_ref_commande_idx` (`ref_commande` ASC),
  CONSTRAINT `fk_ref_commande_etat_preparation`
    FOREIGN KEY (`ref_commande`)
    REFERENCES `6db`.`commande` (`numero_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`illustration_recette` (
  `id_illustration_recette` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_recette` INT UNSIGNED NOT NULL,
  `ref_media` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_illustration_recette`),
  INDEX `fk_ref_recette_idx` (`ref_recette` ASC),
  INDEX `fk_ref_media_idx` (`ref_media` ASC),
  CONSTRAINT `fk_ref_recette_illustration_recette`
    FOREIGN KEY (`ref_recette`)
    REFERENCES `6db`.`recette` (`id_recette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_media_illustration_recette`
    FOREIGN KEY (`ref_media`)
    REFERENCES `6db`.`media` (`id_media`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`illustration_produit` (
  `id_illustration_produit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_produit` INT UNSIGNED NOT NULL,
  `ref_media` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_illustration_produit`),
  INDEX `fk_ref_produit_idx` (`ref_produit` ASC),
  INDEX `fk_ref_media_idx` (`ref_media` ASC),
  CONSTRAINT `fk_ref_produit_illustration_produit`
    FOREIGN KEY (`ref_produit`)
    REFERENCES `6db`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ref_media_illustration_produit`
    FOREIGN KEY (`ref_media`)
    REFERENCES `6db`.`media` (`id_media`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`stock` (
  `id_stock` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `categorie` VARCHAR(45) NULL,
  `quantite_restante` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_stock`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `6db`.`composition_produit` (
  `id_produit` INT UNSIGNED NOT NULL,
  `id_ingredient` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_produit`, `id_ingredient`),
  INDEX `fk_id_produit_idx` (`id_produit` ASC),
  CONSTRAINT `fk_id_produit_composition_produit`
    FOREIGN KEY (`id_produit`)
    REFERENCES `6db`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ingredient_composition_produit`
    FOREIGN KEY (`id_ingredient`)
    REFERENCES `6db`.`stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;